name: CI

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: hydrostack_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Node deps
        run: pnpm install
      - name: Lint & test frontend/backend
        run: |
          pnpm --filter ./apps/frontend lint
          pnpm --filter ./apps/backend test
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python deps
        run: pip install -r apps/calc-api/requirements.txt
      - name: Run calc-api tests
        run: pytest apps/calc-api
